<?php

namespace AppBundle\Repository;

/**
 * CommentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentsRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByProjectID($id){
        return $this->createQueryBuilder('comment')->
        where("comment.projectID = :ID")->
        setParameter("ID",$id)->
        getQuery()->
        getResult();
    }
}
