<?php

namespace AppBundle\Repository;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends \Doctrine\ORM\EntityRepository
{
    public function findArchivedProjects() {
        return $this->createQueryBuilder('project')->
        where("project.isOver = true")->
        getQuery()->
        getResult();
    }
    public function findAllExecutionerProjects() {
        return $this->createQueryBuilder('project')->
        where("project.executioner != 'null'")->
        getQuery()->
        getResult();
    }
    public function findDesignerProjects($fullName) {
        return $this->createQueryBuilder('project')->
        where('project.designer = :fullName')->
        orWhere('project.second_designer = :fullName')->
        andWhere('project.isOver = false')->
        andWhere('project.approved IS NULL OR project.approved = false')->
        setParameter('fullName',$fullName)->
        getQuery()->
        getResult();
    }
    public function findManagerProjects($fullName) {
        return $this->createQueryBuilder('project')
            ->where('project.fromUser = :fullName')->
            andWhere('project.isOver = false')->
            setParameter('fullName',$fullName)->
            getQuery()->
            getResult();
    }
    public function findExecutionerProjects($fullName) {
        return $this->createQueryBuilder('project')
            ->where('project.executioner = :fullName')->
            andWhere('project.isOver = false')->
            setParameter('fullName',$fullName)->
            getQuery()->
            getResult();
    }
    public function findExecutionerArchivedProjects($fullName) {
        return $this->createQueryBuilder('project')
            ->where('project.executioner = :fullName')->
            andWhere('project.isOver = true')->
            setParameter('fullName',$fullName)->
            getQuery()->
            getResult();
    }
    public function findManagerArchivedProjects($fullName) {
        return $this->createQueryBuilder('project')
            ->where('project.fromUser = :fullName')->
            andWhere('project.isOver = true')->
            setParameter('fullName',$fullName)->
            getQuery()->
            getResult();
    }
    public function findDesignerArchivedProjects($fullName) {
        return $this->createQueryBuilder('project')
            ->where('project.designer = :fullName')->
            orWhere('project.second_designer = :fullName')->
            andWhere('project.isOver = true')->
            setParameter('fullName',$fullName)->
            getQuery()->
            getResult();
    }
    public function findAllActiveProjects () {
        return $this->createQueryBuilder('project')->
        where('project.isOver = false')->
        getQuery()->
        getResult();
    }
    public function findAllDesignerProjects ($fullName) {
        //This function is little different. We already have one that finds designer projects by given designer's full name.
        //This function does the same but also gives us the approved projects. The reason behind this is that if we have
        //designer logged in we take all their active projects without archived ones and approved. However if we have
        //LittleBoss logged in and they want to see designer projects they need to also see the approved ones.
        //This is the only difference between this function and the other one.
        return $this->createQueryBuilder('project')->
        where('project.designer = :fullName')->
        orWhere('project.second_designer = :fullName')->
        andWhere('project.isOver = false')->
        setParameter('fullName',$fullName)->
        getQuery()->
        getResult();
    }
}
