<?php

namespace AppBundle\Repository;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends \Doctrine\ORM\EntityRepository
{
    public function findArchivedProjects(){
        return $this->createQueryBuilder('project')->
        where("project.isOver = true")->
        getQuery()->
        getResult();

    }
    public function findExecutionerProjects(){
        return $this->createQueryBuilder('project')->
        where("project.executioner != 'null'")->
        getQuery()->
        getResult();
    }
    public function findDesignerProjects($fullName){
        return $this->createQueryBuilder('project')->
        where('project.designer = :fullName and project.isOver = false')->
        setParameter('fullName',$fullName)->
        getQuery()->
        getResult();
    }
}
