<?php

namespace AppBundle\Repository;

/**
 * ZadanieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ZadanieRepository extends \Doctrine\ORM\EntityRepository
{
}
