services:
    app.service.comments_service:
        class: AppBundle\Service\CommentsService
        autowire: true

    app.service.projects_service:
        class: AppBundle\Service\ProjectService
        autowire: true
    app.service.files_service:
            class: AppBundle\Service\FilesService
            autowire: true
    app.service.users_service:
                class: AppBundle\Service\UserService
                autowire: true